import { ClientDemonstration } from "@/components/i18n/ClientDemonstration";
import { IntlClientProvider } from "@/components/i18n/IntlClientProvider";
import LocaleSwitcher from "@/components/i18n/LocalSwitcher";
import { Providers } from "@/components/providers/Providers";
import { locales } from "@/navigation";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { notFound } from "next/navigation";
import { PropsWithChildren } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LocaleLayout({
  children,
  params: { locale },
}: PropsWithChildren<WithLocale<{}>>) {
  // Validate that the incoming `locale` parameter is valid
  const isValidLocale = locales.some((cur) => cur === locale);
  if (!isValidLocale) notFound();

  return (
    <html lang={locale}>
      <IntlClientProvider locale={locale}>
        <Providers>
          <body className={inter.className}>
            {children}
            <LocaleSwitcher />
            <ClientDemonstration />
          </body>
        </Providers>
      </IntlClientProvider>
    </html>
  );
}
